# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_clone', '0002_auto_20180515_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
