# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_clone', '0002_auto_20180513_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeEmailRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
